services:
  db:
    build: ./db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sampledb
    volumes:
      # Option 1: Bind mount for persistence
      - ./db/data:/var/lib/postgresql/data
      # Option 2: Copy data to host (see scripts/copy_data_to_host.sh)
    entrypoint: ["./scripts/check_existing_data.sh"]
    command: ["postgres"]

  app:
    build: ./app
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: sampledb
