services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"  # MS SQL Server requires a strong password
      ACCEPT_EULA: "Y"                    # Accept the End User License Agreement
      MSSQL_PID: "Express"                # Use the free Express edition
    volumes:
      - mssql_data:/var/opt/mssql         # Persist data using a Docker volume
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-U", "sa", "-P", "YourStrong!Passw0rd", "-Q", "SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: ./app
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 1433
      DB_USER: sa
      DB_PASSWORD: YourStrong!Passw0rd
      DB_NAME: sampledb
    volumes:
      - ./app:/app

volumes:
  mssql_data:
